DROP TABLE IF EXISTS sensor_data;

CREATE TABLE sensor_data(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    laite_id INTEGER NOT NULL,
    sisaan BOOLEAN NOT NULL CHECK (sisaan IN (0,1)),
    aika TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
